#!/usr/bin/env zsh

# Specify the Python interpreter
PYTHON_CMD=python3


$PYTHON_CMD generate_roster.py 10000

export RELEASE_VERSION=v0.0.1
git checkout tags/v0.0.1
$PYTHON_CMD generate_report.py 202304

export RELEASE_VERSION=v0.0.4
git checkout tags/v0.0.4
$PYTHON_CMD generate_report.py 202305

git checkout main
$PYTHON_CMD diff_github.py jmonnette datapoc v0.0.1 v0.0.4

$PYTHON_CMD compare_reports.py 202304 202305
